### ISSUE TITLE
Unable to save Email CC 

### ISSUE THREAD

**Issue by BorisovskiP** [DominicWatts/EmailCC#3]
We are unable to save the emails in the backend , thus the module does not work as intended.

We found out that during the save process, the attribute code `email_cc` is not set to the customer attribute set.  

We also found out that there is not input field in the `customer/account/edit/` page to set the CC'ed emails.

This was tested on Magento 2.3.5-p2

**Comment by DominicWatts** [comment]
Extension was written for 2.2

I've updated setup to create attribute for 2.3/2.4 - check 1.1.0 release https://github.com/DominicWatts/EmailCC/releases/tag/1.1.0

I've amended composer.json to hopefully throw version errors if using wrong version

Template update came through for me on 2.3.5 Luma theme with no modification

![image](https://user-images.githubusercontent.com/7295705/95004048-1f3e7e80-05de-11eb-9660-756e3e28481e.png)

I've not had a chance to check the CC functionality itself but not seeing any obvious reason shouldn't work under latest version

**Comment by BorisovskiP** [comment]
Thanks, as the issues we had are now fixed, i will close the issue.
